**Завдання 2.2. Попередня обробка нових даних**

In [ ]:
import numpy as np
from sklearn import preprocessing

input_data = np.array([[-1.3, 3.9, 6.2],
                        [-4.9, 2.2, -4.3],
                        [-2.2, 6.5, 4.1],
                        [-5.2, -3.4, -5.2]])

**Бінарізація**

In [ ]:
data_binarized = preprocessing.Binarizer(threshold=2.2).transform(input_data)
print("\n Binarized data:\n", data_binarized)



 Binarized data:
 [[0. 1. 1.]
 [0. 0. 0.]
 [0. 1. 1.]
 [0. 0. 0.]]


**Виключення середнього**

In [ ]:
print("\nBEFORE: ")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

data_scaled = preprocessing.scale(input_data)
print("\nAFTER: ")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))



BEFORE: 
Mean = [-3.4  2.3  0.2]
Std deviation = [1.68374582 3.62973828 5.01547605]

AFTER: 
Mean = [1.66533454e-16 5.55111512e-17 0.00000000e+00]
Std deviation = [1. 1. 1.]


**Масштабування**

In [ ]:
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nМin max scaled data:\n", data_scaled_minmax)



Мin max scaled data:
 [[1.         0.73737374 1.        ]
 [0.07692308 0.56565657 0.07894737]
 [0.76923077 1.         0.81578947]
 [0.         0.         0.        ]]


**Нормалізація**

In [ ]:
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nl1 normalized data:\n", data_normalized_l1)
print("\nl2 normalized data:\n", data_normalized_l2)



l1 normalized data:
 [[-0.11403509  0.34210526  0.54385965]
 [-0.42982456  0.19298246 -0.37719298]
 [-0.171875    0.5078125   0.3203125 ]
 [-0.37681159 -0.24637681 -0.37681159]]

l2 normalized data:
 [[-0.17475265  0.52425796  0.83343572]
 [-0.71216718  0.31974853 -0.62496303]
 [-0.2752151   0.81313551  0.51290086]
 [-0.64182859 -0.41965715 -0.64182859]]
